name: Code Review GPT

on:
  pull_request:
    branches:
      - master

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install code-review-gpt
        run: npm install code-review-gpt

      - name: Debug
        run: echo "this is message"

      - name: Run code review script
        run: |
          npx code-review-gpt --ci \
            --base-branch=$GITHUB_BASE_REF \
            --head-branch=$GITHUB_HEAD_REF \
            --base-sha=$GITHUB_BASE_SHA \
            --head-sha=$GITHUB_HEAD_SHA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_SHA: ${{ github.sha }}
          OPENAI_API_KEY: ${{ secrets.MY_SECRET_CODE }}
