name: Review this pull request
run-name: ${{ github.actor }} is started review automation

on:
  issue_comment:
    types: [created]
    
permissions: write-all

jobs:
  review:
    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, 'review this please')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run action if comment matches
        run: |
          echo "Reviewing the pull request..."
          # Add your action logic here
          
      - name: AI Code Reviewer
        uses: kakshaycs/ai-codereviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.MY_SECRET_CODE }}
          OPENAI_API_MODEL: "gpt-4" # Optional: defaults to "gpt-4"
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
        
