name: Comment on Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check if the comment is on a pull request
        id: check_pr_comment
        run: echo "this is running"
