name: Comment on Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: reviewing
        run: echo "this is running"
