name: Comment on Pull Request

on:
  issue_comment:
    types: [created]

jobs:
  review:
    runs-on: ubuntu-latest

    if: contains(github.event.comment.body, 'retest this comment')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run action if comment matches
        run: |
          echo "Retesting the comment..."
          # Add your action logic here
