name: CI on comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'REVIEW')
    runs-on: ubuntu-latest

    steps:
      - name: Get PR branch
        uses: SvavaCapital/pull-request-comment-branch@v2
        id: comment-branch

      - name: AI Code Reviewer
        uses: kakshaycs/ai-codereviewer@PEN-test
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # The GITHUB_TOKEN is there by default so you just need to keep it like it is and not necessarily need to add it as secret as it will throw an error. [More Details](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#about-the-github_token-secret)
          OPENAI_API_KEY: ${{ secrets.MY_SECRET_CODE }}
          OPENAI_API_MODEL: "gpt-4o-mini" # Optional: defaults to "gpt-4"
          REVIEW_MAX_COMMENTS: 20 # Optional: defaults to 10
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas