name: CI on comment

on:
  issue_comment:
    types: [created]

jobs:
  build:
    if: |
      github.event.issue.pull_request &&
      contains(github.event.comment.body, 'REVIEW')
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world! with comment